<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/16 13:00:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
