dev:
  doctrine:
    class: sfDoctrineDatabase
 
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jobeet;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock'
      username: root
      password: root
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jobeet_test;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock'
      username: root
      password: root
