<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/26 10:43:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
